version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: mobile-cloud-lab_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis:latest
    container_name: mobile-cloud-lab_redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  app-network:
    driver: bridge
    name: mobile-cloud-lab_app-network