AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_NAME: UploadProductFunction
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ProductDataBucket
            Events: s3:ObjectCreated:*
  GetAllProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_NAME: GetAllProductsFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /products
            Method: GET
  ProductDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: product-data-bucket